export { Homepage } from "./Homepage/Homepage";
export { Productpage } from "./Productpage/Productpage";
export { Profile } from "./Profile/Profile";
export { Wishlist } from "./Wishlist/Wishlist";
export { Cartpage } from "./Cartpage/Cartpage";
export { Checkoutpage } from "./Checkoutpage/Checkoutpage";
export { ForgetPassPage } from "./Auth/ForgetPassPage";
export { LoginPage } from "./Auth/LoginPage";
export { SignupPage } from "./Auth/SignupPage";
